services:
  - type: web
    name: pocket-summarizer
    env: python
    region: virginia
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --worker-class gevent --workers 3
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PERPLEXITY_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: pocket-summarizer-redis
          property: connectionString

  - type: redis
    name: pocket-summarizer-redis
    region: virginia
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    plan: free
